name: .NET

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4.2.2
            -   name: Setup .NET
                uses: actions/setup-dotnet@v4.1.0
                with:
                    dotnet-version: 7.0.x
            -   name: Restore dependencies
                run: dotnet restore
            -   name: Test
                run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' /p:ExcludeByAttribute="Tomlet.Attributes.NoCoverageAttribute"
            -   name: Upload test coverage
                uses: coverallsapp/github-action@v2.3.4
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    path-to-lcov: ./Tomlet.Tests/lcov.info
            -   name: Build
                run: dotnet build -c Release
            -   name: Upload NuGet Artifact
                uses: actions/upload-artifact@v4.5.0
                with:
                    name: Tomlet.nupkg
                    path: Tomlet/bin/Release/*.nupkg
            -   name: Upload to NuGet
                if: contains(github.event.head_commit.message, '[publish]') == true && github.event_name == 'push'
                env:
                    NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
                run: dotnet nuget push ./Tomlet/bin/Release/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY